name: mafia bot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Repositoriyni yuklash
      uses: actions/checkout@v3

    - name: Python o‘rnatish
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Kerakli kutubxonalarni o‘rnatish
      run: pip install pyTelegramBotAPI

    - name: Botni ishga tushirish
      run: python main.py
